version: "3"
services:
  app:
    build:
      context: ./
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
      - SPRING_JPA_GENERATE_DDL
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: bitnami/postgresql:11
    environment:
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
    volumes:
      - postgresdb:/bitnami/postgresql
    restart: always
volumes:
  postgresdb:
